<<<<<<< HEAD

'use client'

import { Geist, Geist_Mono } from "next/font/google"
import '@/app/globals.css'
import { Navbar } from "@/components/navbar"
import {  Providers } from "@/providers/provider"
import { ToastContainer } from "react-toastify"
import 'react-toastify/dist/ReactToastify.css'
import { usePathname } from "next/navigation"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})


const NoNavRoutes = [
	"/dashboard",
	"/register",
	"/login"
]

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {

	const pathname = usePathname()

	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable}`}>
				{!NoNavRoutes.some(route => pathname.startsWith(route)) && <Navbar />}
				<Providers>
					<main className="flex-grow container mx-auto px-4 py-8">
						{children}
					</main>
				</Providers>
				<ToastContainer position="bottom-right"/>
			</body>
		</html>
	)
=======
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
>>>>>>> 9a6bb5eaf5fc71426c75b15bc069315aeb029533
}
